DROP TABLE IF EXISTS vehicles;
CREATE TABLE IF NOT EXISTS public.vehicles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model    VARCHAR(255),
    cubic_centimeters DOUBLE PRECISION,
    released          INTEGER,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);