DROP TABLE IF EXISTS vehicles;

CREATE TABLE IF NOT EXISTS vehicles
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    model             VARCHAR(255)                            NOT NULL,
    cubic_centimeters DOUBLE PRECISION,
    released          INTEGER,
    CONSTRAINT vehicles_pk PRIMARY KEY (id)
);